"""empty message

Revision ID: 3429fb7f6722
Revises: 6792b6fa8399
Create Date: 2018-07-16 15:36:48.034140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3429fb7f6722'
down_revision = '6792b6fa8399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('img_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'img_state')
    # ### end Alembic commands ###
