"""empty message

Revision ID: 69da45fb082d
Revises: c7a654f8c49b
Create Date: 2018-07-06 16:51:52.853037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69da45fb082d'
down_revision = 'c7a654f8c49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paramas', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paramas', 'comments')
    # ### end Alembic commands ###
